Table users {
  id integer [primary key]
  name string
  username string [note: "nullable"]
  email string
  email_verified_at datetime [note: "nullable"]
  password string
  avatar string [note: "nullable"]
  status boolean
  created_by integer [note: "nullable"]
  updated_by integer [note: "nullable"]
  timezone string [note: "nullable"]
  last_login_at datetime [note: "nullable"]
  created_at datetime
  updated_at datetime
}

Table products {
  id integer [primary key]
  name string
  code string
  type string
  description text [note: "nullable"]
  image string [note: "nullable"]
  is_active boolean
  is_default boolean
  created_by integer [note: "nullable"]
  updated_by integer [note: "nullable"]
  created_at datetime
  updated_at datetime
}

Table product_units {
  id integer [primary key]
  product_id integer
  unit_price double
  total_price double
  quantity double
  conversion_factor double
  unit_id integer [note: "nullable"]
  brand_id integer [note: "nullable"]
  supplier_id integer [note: "nullable"]
  created_at datetime
  updated_at datetime
}

Table product_images {
  id integer [primary key]
  product_unit_id integer
  image string
  is_default boolean
  created_at datetime
  updated_at datetime
}

Ref: product_units.product_id > products.id
Ref: product_units.unit_id > units.id
Ref: product_units.brand_id > brands.id
Ref: product_units.supplier_id > suppliers.id
Ref: product_images.productUnit_id > products.id
